import argparse
import json

def main():
    parser = argparse.ArgumentParser(description="An example Layer 3 Tool for the Agent Skill Framework.")
    parser.add_argument("--input", type=str, required=True, help="Input string to process")
    
    args = parser.parse_args()
    
    # Process data deterministically
    result = {
        "status": "success",
        "processed_input": args.input.upper(),
        "message": "This is a deterministic output generated by a Layer 3 Tool."
    }
    
    # Output structured data
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
